### ISSUE TITLE
Suggestion list

### ISSUE THREAD

**Issue by SpiderKolo** [Luligabi1/Incantationem#1]
Hey! I like your enchantment set!
I have few suggestions for the enchantments if you don't mind, mostly a take on balancing existing enchantments:

Bane of the Swines - A new second most situational enchantment on sword after Bane of Antropods! Cool!
Seriously tho... cool idea for an enchantment!

It would help make this enchantment shine more if you could also deal damage to Zombified Piglins. Sure, they are undead, but... they are also pigs...

You also could make this enchantment have a unique interaction with the mob type it's supposed to deal with. Bane of Antropods also slows down antropods (not like they won't die immediately first).
For Pig kin... you could apply another potion effect. Weakness would make a lot of sense as lowering damage of the Offensive pigs would help greatly while dealing with them.

Sadly this enchantment doesn't work. Tested it on all pig kind and few non-pig kind to make sure the conditions were not reversed.

Bunny's Hop - This one is relatively simple... but I feel like also not interesting enough.

For starters you made player be affected by Jump Boost. That means you can't stack it with potions since you are already affected by potion.
And then jumps on command by just wearing those boots? Anywhere? Sounds busted.
Keep in mind there is a vanilla enchantment which let's you move faster, but the condition is to be walking on Soul Blocks. While doing so you also keep loosing durability on said boots.
That enchantment was fine, because it is a treasure enchantment, that means no randomly rolling this on enchanting table and getting very situational enchantment. It also let's you deal with the Soul Sands in Nether (no more slowness) AND you move faster on it.

Here is my suggestion for balance change for the Jumping enchantment:

Make it only work while standing on specific set of blocks. Since we are referring to Bunny... perhaps you could choose blocks where you may encounter Bunnies/Rabbits? So... Grass, Sand, maybe different variants of Dirt...
Now we have boots for mobility in Overworld surface.
You could rename it to "Grass Hopper" and make it work exclusively on Grass (and maybe other Dirt variants). Up to you.

You could even make a "Curse or Rabit Foot" and force player to constantly jump on moving and lose saturation on said jumps.
But about that maybe later...

You might notice that this enchantment became more situational with those changes, but not too situational.
It is still going to be extremely flexible when climbing surface of Overworld, since majority of it is covered in Grass or other Dirt variants. That's if we exclude sand form equation.
I think it should be a Treasure Enchantment because easy and strong mobility buff accessible from just enchanting table would be unbalanced.

Forging Touch - I think this enchantment is a bit busted in some scenarios.
Basically when you have this enchantment, you can turn your cobblestone into stone from time to time. You sacrifice Durability of your tools instead of actual fuel. How bad can this be?

Well... it can be broken.

Even if we go with a chance like you did on this one... there are still some blocks you can easily cook without to even having to worry about durability!
You can cook potatoes rapidly by placing and picking them up with forged tool. I somehow lost few potatoes as well so that's not a good sign...
Kelp can me picked up easily. This one also grows everywhere in oceans. With this enchantment, you will never go hungry ever!

But the thing is... we can't quite change that behavior, because Fortune also can be used on crops. Surely you can't multiply one potato into multiple by just spam-placing-and-breaking same crop over and over again, but you also won't be loosing durability there and you still can gather benefits from this enchantment.

Maybe if player had to wait till crop grows then it would be more balanced? That would fix Potato issue bu you still have the Kelp.

Personally I'm not a fan of chance based enchantment there, but considering how much fuel you might save with this one... maybe it's a must in this case.

What could possibly reduce the usage of the enchantment could maybe be excluding it to Treasure Enchantment just like with "Bunny's Hop". This one seems to be very fitting to exclude to only Nether too as it cooks for us the blocks.

Last cosmetic change: Instead of message, maybe show fire particles going from the block you mined to let player know that the enchantment works?
Message will make players get tired quickly, but they will always appreciate a nice visual representation of what is happening.

Charmed - this one confuses me the most...
If I got it right... you are supposed to get more lucky enchantment rolls.
What it surely does is apply Luck effect on player. This makes all loot-tables slightly more generous for the player with that effect. Every new chest you gonna open for the first time with randomly generated loot will have greater rewards.
I... don't know about this one.

Sure, buff is slight, but you can just carry this for free and just holding it gives you Luck. Any time you want.
It have similar issues with Bunny Hop as it provides a potion effect. This time un-craftable potion effect, but one non the less.

I would personally replace the effect completely, because it doesn't do enough on it's own and feels like a waste if you roll this over anything else.
On the other hand if you already have everything you need from enchanting table, you can gather even more loot from chests.

New effect idea:
How about... when we trade with Villager, prices fall faster while wearing set of armour enchanted with this buff.
It makes sense, because the enchantment makes you look better.
Tho would probably need a slight modification to name - from "Charmed" to "Charming".
Don't make this passive price reduction tho, because then players will abuse it on any trade they will ever make with any villager they get their hands on. Force the players to interact with the Villagers first.

You could even make it work on Piglins too: Maybe they barter more rare items for Golden Ingots?

In this case it feels like a treasure enchantment but specifically only obtainable from Villager trading.
Maybe it get randomly applied on some of the Villager tools and armor pieces.

Decay - this enchantment feels extremely overpowered.
At level I - does barely anything. Fire Aspect I at least gives you cooked meat if you kill the mob with it.
But then, you increase both chance, amplifier, duration... all at once.

I feel like this should be heavily nerfed. Fire Aspect can't hurt mobs immune to fire, this looks like if the effect was weak enough, it would be utilized well enough. Keep in mind Wither effect will apply to almost anything.

You should increase only one of the aspects of the enchantment at the time. Pick Duration (probably less overpowered), Strength of effect (makes enchantment better as it does same job as longer lasting weaker variant... but faster) OR chance.
In fact, if effect is weak enough, I would personally set the chance to be 100% always. Otherwise the ability is unreliable in the most dire of situations.

And that's without even asking if players should have access to the effect in the first place.
Not against it personally, some people might think it's not fitting.

Last Stand - This enchantment will only help you if you have full set or enchanted Diamond or better armor, all pieces with Protection IV and you are surrounded by a bunch of weak mobs with seemingly no escape.
Except... not really.

Conditions for this enchantment to be working are very specific and way too close to dying to be able to even benefit them.
At level 1 I got the effect ONCE. In the last, killing blow.
At level 2 I got devoured, but got effect twice, maybe three times.
At level 3... still not impressive.

Reward could be a game changer... but it's way to dangerous to risk using it.
And carrying an enchantment which tries to help you only when you are about to die and still doesn't help much... doesn't sound neat.

Concept on paper sounds cool tho - You get magical adrenaline rush as you fight for your life. Suddenly... you get angry and desperate. This is your last chance to survive, there is only one way out of it, and it is to fight to the death.

In practice you have at least two skeletons aiming for your head as a creeper is already behind you, all while you were beating an undead child to death.
It only make sense if you take very little damage so you might survive few more hits. And even then - it's all based on chance.

How about it always triggers at medium range of health, say... 4 hearts?
With solid protection, 4 Hearts is enough to take one more hit and survive.
We don't increase the range at which it triggers for every level... we increase the strength of effect for every level.
Level I of the enchantment would give us effect at level I
Level II enchantment = Level II effect
Level III = Level III

Important note - you trigger this ability only once after you fell lower than 4 Hearts. In order to trigger it again, you need to get to the full health and only then you can use this enchantment again.

Which effect would be most fitting?
That might be difficult to say. Strength fits if you want to go for more aggresive stand.

Magnetic - this enchantment is alright.
Small thing worth noting: Enchantment doesn't seem to stack on multiple pieces.
Only one piece with greatest level of enchantment will really matter in your gear.

There is a simple fix - make this enchantment only be compatible with Chestplate OR Pants.
That way you don't have to worry about non-stacking with multiple armor pieces and you also declutter enchantment list from enchanting table.
There isn't a whole lot of good enchantments which would exclusively go on Pants only, I fee like magnetic pockets is the closest thing we might get.

All items also are going to a offset position from character for some reason. You still can pickup the items, but it doesn't look pleasant when item goes on a side before actually going to your inventory. Or when trying to reach the player.

One major design flaw: with Magnetic enchantment, you can travel with a lot of items floating around your avatar. You can potentially move... honestly as much of the material as you want up to despawn time in 5 minutes.
Perhaps Magnetic should only pull items while you can still fit in items?

Reaping Rod - This one is weird but okay.
It almost works... except one punch to early.
I got it trigger before I actually killed the mob.

I don't know why punching with a Fishing Rod of all things is supposed to give you such good buffs, but I guess it's an interesting concept...

I was hoping (when I saw the name of enchantment for the first time) that it would increase the force you fish items and mobs with while reducing the durability use on performing such actions. Fishing Rod is underutilized in fighting.

I'm gonna say this is a very interesting enchantment.

Retreat - Slightly too good.
This enchantment have similar issues to few others where first level almost never works, second is desant, third is bonkers.
I would honestly think it needs a lot of similar changes to Last Stand enchantment, except swap in offensive effect to more mobility.

Alternatively, perhaps you could implement a system where you naturally move faster the less health you have.
Tho in that case we no longer have the sudden urge to run away, so probably I would go with first idea for Retreat...

Venomous - We have Lingering Potions you can use to cover arrows in them.
I don't know if we need another enchantment which replaces potions.

Other that that, a lot of mobs are immune to Poison anyway, which includes all Spiders AND Undead.
It's worse than Flame, because - again - it's inconsistent and triggers only sometimes, where Flame is always active but it's inefficient in water and when it's raining. It also cooks meat when you kill an animal with it.

I will look into curses later when I get more time.
I hope you will find this post useful.
I'm wishing you good luck with writting the mod. :)

**Comment by Luligabi1** [comment]
Hi, thank you for the great suggestions! I'm working on another mod at the moment, but I'll eventually update the mod to include most of your suggestions.

> Charmed - this one confuses me the most...
If I got it right... you are supposed to get more lucky enchantment rolls.
What it surely does is apply Luck effect on player. This makes all loot-tables slightly more generous for the player with that effect. Every new chest you gonna open for the first time with randomly generated loot will have greater rewards.
I... don't know about this one.

Sure, buff is slight, but you can just carry this for free and just holding it gives you Luck. Any time you want.
It have similar issues with Bunny Hop as it provides a potion effect. This time un-craftable potion effect, but one non the less.

I would personally replace the effect completely, because it doesn't do enough on it's own and feels like a waste if you roll this over anything else.
On the other hand if you already have everything you need from enchanting table, you can gather even more loot from chests.

The charmed enchantment increases the odds of getting good effects on enchantments of the mod too. But I might add the villager/piglin idea later too.

**Comment by Luligabi1** [comment]
Ok, I'm starting to work on this issue. Here's an (hopefully) updated list of what's complete:

- [x] Add slowness to Bane of the Swine
- [x] Change Bunny's Hop to work on grass/dirt blocks only
- [x] Mark Forging Touch as treasure
- [x] Nerf decay overall (not sure by what way yet)
- [x] Change triggering mechanism of Last Stand
- [x] Make Magnetic leggings-only
- [x] Fix Reaping Rod triggering a hit early
- [x] Change Retreat mechanism entirely

**Comment by Luligabi1** [comment]
All changes have been completed as of the above post. Thank you! Expect these to be in place on the 1.1 patch, coming tomorrow-ish for 1.17+!
