### ISSUE TITLE
Charmed's description doesn't describe its effect well

### ISSUE THREAD

**Issue by saltyseadoggo** [Luligabi1/Incantationem#11]
Charmed's description doesn't make it clear that it apples *the* vanilla Luck effect, and it also doesn't explain what the vanilla Luck effect applies. My girlfriend and I were confused about what exactly it improves luck on. I looked into the code to discover that it just applies the vanilla Luck effect, which, as you can read here https://minecraft.fandom.com/wiki/Luck, only affects fishing loot.
I would like to see the Charmed description that shows when Enchantment Descriptions is loaded be changed to better describe the effect. Here's a description you can use:

`Applies the vanilla Luck effect, which increases loot quality while fishing and in modded loot tables that use it.`

**Comment by Luligabi1** [comment]
> Applies the vanilla Luck effect, which increases loot quality while fishing and in modded loot tables that use it.

This is not entirely accurate either. All luck-based enchantments and curses on Incantationem also use the (un)luck effect to determine the odds. I do however agree it's not entirely clear the way it was written. I'll think of something better eventually 🙂

**Comment by Luligabi1** [comment]
Changing this to "Increases loot quality while fishing and your luck with Incantationem's enchantments/curses." on next release, hope it clears the confusion!
