### ISSUE TITLE
Newest 1.19.2 version causing duplicate block drops.

### ISSUE THREAD

**Issue by ConqAra** [Luligabi1/Incantationem#18]
When the mod is installed, everytime I break a block instead of 1 block dropping 2 drop instead.

**Comment by Luligabi1** [comment]
**_UGHHHHHHHHHHHHHHHHHHHHH_** god I should test stuff more. I'll try to release a fix for this today.

**Comment by Luligabi1** [comment]
Releasing a fix for this on CF and Modrinth soon.
