### ISSUE TITLE
[1.18.2/1.19.2] Allow Fortune to work with Forging Touch if applicable

### ISSUE THREAD

**Issue by ConqAra** [Luligabi1/Incantationem#21]
when mining ores such as gold/iron or ancient debris, it'd be nice when the forging touch is applied, if a pickaxe has fortune on it as well it would apply the fortune effect alongside the forging touch effect.

**Comment by ConqAra** [comment]
Seems to also make sense since this is a treasure enchantment as well.

**Comment by Luligabi1** [comment]
I'll see what I can do

**Comment by Luligabi1** [comment]
Added in `2.0.+1.21`
