### ISSUE TITLE
[1.18.2] Forging Touch incompatible with Fabric Enchantments installed

### ISSUE THREAD

**Issue by ConqAra** [Luligabi1/Incantationem#22]
Tested on 1.18.2, Didn't see anything in the log but when these two mods are installed forging touch will NOT work. 

Mod: [https://github.com/Safrodev/fabricenchantments/](https://github.com/Safrodev/fabricenchantments/)

**Comment by Luligabi1** [comment]
Does this happen on 1.19 too? A patch has been released that adresses a similar mixin incompatibility on a mixin Forging Touch uses. I don't plan to backport said patch to 1.19 atm, unless someone is willing to PR it.

**Comment by ConqAra** [comment]
According to the mod developer of fabric enchantments, they will be doing a simple fix on their side for 1.19.2.

**Comment by Luligabi1** [comment]
> According to the mod developer of fabric enchantments, they will be doing a simple fix on their side for 1.19.2.

Actually, I double checked and I did release this patch for 1.18.2 too. Were you testing with version `1.1.6`?

**Comment by ConqAra** [comment]
Yes, wasn't that the latest version?

**Comment by Luligabi1** [comment]
> Yes, wasn't that the latest version?

It is (it's the version with the patch I mentioned previously, I just thought I hadn't released it for 1.18.2).

> According to the mod developer of fabric enchantments, they will be doing a simple fix on their side for 1.19.2.

So the issue is on Fabric Enchantments' end, right? They most likely will have to change their mixins the same way I did, using `ModifyReturnValue` to allow mod compatibility.
