### ISSUE TITLE
Bane of swine name has wrong identifier

### ISSUE THREAD

**Issue by Akinesis** [Luligabi1/Incantationem#30]
The identifier for Bane of Swine in the lan file is : 
   enchantment.incantationem.swine_bane 
but somewhere in your code you use : 
  enchantment.incantationem.bane_of_the_swine

Resulting in a non-translated string and showing the identifier instead.
![image](https://github.com/Luligabi1/Incantationem/assets/6651712/4ce99fa7-a6db-4cbf-b433-eacf49582d66)

**Comment by Luligabi1** [comment]
Oops, forgot to rename this on the language files when I changed this enchantment's ID 😅 This is fixed on `2.0.3+1.21`
