### ISSUE TITLE
WHERE DECAY?? 1.21.1

### ISSUE THREAD

**Issue by Siluet3656** [Luligabi1/Incantationem#31]
Decay doesn't appear on enchanting table (1.21.1). MB Fuse shot too, but I'm not sure.

**Comment by Luligabi1** [comment]
By default, neither of them are available through the enchanting table, only throught treasure chests and trades. You can use datapacks to alter this, you'll only need to add `incantationem:decay` and `incantationem:fuse_shot` to `#minecraft:in_enchanting_table`

**Comment by Siluet3656** [comment]
Ty for your answer. It's different for version 1.18.2 because i got this enchant via enchanting table on this game version and it confused me. Additionaly mod wiki said i can get it like this. понедельник, 07 октября 2024г., 20:24 +04:00 от Luiz Feikes  ***@***.*** :
