### ISSUE TITLE
[Suggestion] Add Enchantment Descriptions 

### ISSUE THREAD

**Issue by kalinzange** [Luligabi1/Incantationem#4]
If it's possible to add enchantment description on [Enchantment Descriptions Mod](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)

![image](https://user-images.githubusercontent.com/38161086/126243058-473d8c72-20d9-4bb5-a9cf-6baf4b237409.png)

**Comment by Luligabi1** [comment]
I'll have to check how support is handled, but I'll add it into my TODO list 👍🏼 I'll comment again when it's added.

**Comment by Luligabi1** [comment]
Hey, this is currently implemented in the 1.17 branch, will launch it on Curse on the next few days. Thank you for the suggestion!
